[versions]
application_id = "com.ohyooo.qrscan"
min_sdk = "23"
target_sdk = "36"
compile_sdk = "36"
version_code = "10"
version_name = "2.10"

agp = "8.13.0"
kotlin = "2.2.20"
workmanager = "2.8.1"
serialization = "1.9.0"

compose_compiler_version="1.5.15"

accompanist = "0.36.0"
compose = "1.9.1"
camerax = "1.5.0"


[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
kgp = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ks = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
cc = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
# kotlin
# https://github.com/Kotlin/kotlinx.coroutines/releases
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
# https://github.com/Kotlin/kotlinx.serialization/releases
json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }


# Kotlin
kotlinx_coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
kotlinx_coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
kotlinx_serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"

# Google
google_material = "com.google.android.material:material:1.13.0"
google_barcode = "com.google.mlkit:barcode-scanning:17.3.0"
accompanist_pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist_pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }

# AndroidX
androidx_core-ktx = "androidx.core:core-ktx:1.17.0"
datastore_preferences = "androidx.datastore:datastore-preferences:1.1.7"
activity_compose = "androidx.activity:activity-compose:1.11.0"
fragment_ktx = "androidx.fragment:fragment-ktx:1.8.9"
lifecycle_viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.9.3"
profileinstaller = "androidx.profileinstaller:profileinstaller:1.4.1"
navigation_compose = "androidx.navigation:navigation-compose:2.9.4"

# Compose
compose_compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose_compiler_version" }
compose_foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose_material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose_material-icons-extended = "androidx.compose.material:material-icons-extended:1.7.8"
compose_runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose_ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose_ui_tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose_ui_tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose"}

# Camera
camera_camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camera_lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camera_view = { module = "androidx.camera:camera-view", version.ref = "camerax" }


[bundles]
all = ["kotlinx_coroutines_android" ,"google_material" ,"google_barcode" ,"accompanist_pager" ,"accompanist_pager_indicators" ,"androidx_core_ktx" ,"datastore_preferences" ,"activity_compose" ,"fragment_ktx" ,"lifecycle_viewmodel_compose" ,"kotlinx_serialization" ,"kotlinx_coroutines_core" ,"profileinstaller" ,"navigation_compose" ,"compose_compiler" ,"compose_foundation" ,"compose_material" ,"compose_material_icons_extended" ,"compose_runtime" ,"compose_ui" ,"compose_ui_tooling_preview" ,"compose_ui_tooling","camera_camera2" ,"camera_lifecycle" ,"camera_view"]

