name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDDHHmmss'
     
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
     
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease
     
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 5
          delete_tags: true

      - name: Create Release
          run:
            set -x
            assets=()
            for asset in app/build/outputs/apk/release/*.apk; do
              assets+=("-a" "$asset")
            done
            assets+=("-a" "app/build/outputs/mapping/release/mapping.txt")
            tag_name="${GITHUB_REF##*/}"
            hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 10
          keep_minimum_runs: 2
